#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import argparse
import json
import math
import re
from pathlib import Path
from statistics import mean


METRIC_DEFINITIONS = {
    "throughput.instantaneous_mbps_cpu": "CPU path instantaneous cluster throughput per TTI from scheduler internal rate arrays; this is not packet-served throughput.",
    "throughput.instantaneous_mbps_gpu": "GPU path instantaneous cluster throughput per TTI from scheduler internal rate arrays; this is not packet-served throughput.",
    "throughput.long_term_sum_mbps_cpu": "CPU path cluster long-term throughput state from scheduler avg-rate arrays; this is a scheduler-internal fairness state.",
    "throughput.long_term_sum_mbps_gpu": "GPU path cluster long-term throughput state from scheduler avg-rate arrays; this is a scheduler-internal fairness state.",
    "throughput.per_ue_avg_mbps_cpu": "CPU path per-UE long-term average rate from scheduler state arrays; not the same as packet-served UE throughput.",
    "throughput.per_ue_avg_mbps_gpu": "GPU path per-UE long-term average rate from scheduler state arrays; not the same as packet-served UE throughput.",
    "traffic.flows": "Number of traffic flows with traffic generation enabled.",
    "traffic.generated_pkts": "Total packets generated by the traffic model across all enabled flows.",
    "traffic.generated_bytes": "Total traffic bytes generated by the traffic model across all enabled flows.",
    "traffic.accepted_bytes": "Total bytes accepted into the traffic model queueing pipeline before MAC service.",
    "traffic.dropped_bytes": "Total traffic bytes dropped by the traffic model before reaching the MAC buffer.",
    "traffic.flow_queued_bytes": "Residual bytes still left in the pre-MAC flow queues at the end of the run.",
    "traffic.mac_buffer_bytes": "Residual bytes still present in the MAC buffer arrays at the end of the run.",
    "traffic.expired_bytes": "Total bytes removed from the MAC packet queues because their packet age exceeded the configured TTL.",
    "traffic.expired_packets": "Total packets removed from the MAC packet queues because their packet age exceeded the configured TTL.",
    "traffic.expiry_drop_rate": "Fraction of generated bytes that eventually expired due to packet TTL.",
    "traffic.served_bytes_est": "Estimated bytes successfully drained from the queueing system, computed as accepted_bytes - flow_queued_bytes - mac_buffer_bytes - expired_bytes.",
    "traffic.goodput_bytes": "Successfully decoded payload bytes, accumulated only from transport blocks with tbErr=0.",
    "traffic.offered_mbps": "Average offered traffic load over the whole run, computed from generated bytes and simulated time.",
    "traffic.served_mbps_est": "Average served throughput estimate over the whole run, computed from served_bytes_est and simulated time.",
    "traffic.goodput_mbps": "Average goodput over the whole run, computed from successfully decoded bytes and simulated time.",
    "traffic.drop_rate": "Fraction of generated bytes dropped before entering the MAC buffer.",
    "traffic.queue_delay_est_ms": "Backlog-based queueing delay estimate at the end of the run, computed as residual MAC bytes divided by average served throughput; not a packet timestamp average.",
    "traffic.packet_delay_served_pkt_count": "Number of packets fully drained from the MAC packet queue tracker and therefore included in packet-level delay statistics.",
    "traffic.packet_delay_pending_pkt_count": "Number of packets or residual packet fragments still pending in the MAC packet queue tracker at the end of the run.",
    "traffic.packet_delay_mean_ms": "Mean packet-level delay in milliseconds for fully served packets, measured from enqueue TTI to the TTI where the last byte leaves the MAC queue tracker.",
    "traffic.packet_delay_p50_ms": "Median packet-level delay for fully served packets.",
    "traffic.packet_delay_p90_ms": "90th percentile packet-level delay for fully served packets.",
    "traffic.packet_delay_p95_ms": "95th percentile packet-level delay for fully served packets.",
    "traffic.packet_delay_max_ms": "Maximum packet-level delay among fully served packets.",
    "global_kpi.cluster_sum_throughput_mbps": "Cluster served throughput used for RR/PF comparison. When TRAFFIC_KPI is available, this matches traffic.served_mbps_est.",
    "global_kpi.cluster_goodput_mbps": "Cluster goodput computed from successfully decoded bytes. When TRAFFIC_GOODPUT is available, this matches traffic.goodput_mbps.",
    "global_kpi.cluster_spectral_efficiency_bps_per_hz": "Cluster served throughput divided by the configured carrier bandwidth in Hz. Because throughput is summed across cells while bandwidth is per carrier, this is a cluster-level spectral-efficiency indicator rather than a single-link Shannon efficiency.",
    "global_kpi.average_ue_throughput_mbps": "Cluster throughput divided by UE count.",
    "global_kpi.average_ue_goodput_mbps": "Cluster goodput divided by UE count.",
    "global_kpi.global_tb_bler": "Transport-block error rate aggregated over all scheduled transmissions.",
    "global_kpi.global_predicted_bler_weighted": "Weighted mean of predicted BLER across UEs, weighted by scheduled transmission count.",
    "global_kpi.global_tx_success_rate": "Fraction of scheduled transport blocks that were decoded successfully.",
    "global_kpi.total_generated_bytes": "Sum of generated_bytes over all UE flows.",
    "global_kpi.total_expired_bytes": "Total bytes expired by the packet TTL mechanism.",
    "global_kpi.total_expired_packets": "Total packets expired by the packet TTL mechanism.",
    "global_kpi.expiry_drop_rate": "Expired-byte ratio aggregated over the whole run.",
    "global_kpi.total_mac_buffer_bytes": "Sum of mac_buffer_bytes over all UEs at the end of the run.",
    "global_kpi.residual_buffer_ratio": "Residual MAC buffer bytes divided by total generated bytes.",
    "global_kpi.non_residual_buffer_ratio": "One minus residual_buffer_ratio; indicates the share of generated bytes no longer left in the queueing system, including TTL-expired bytes.",
    "global_kpi.served_buffer_ratio": "Estimated served_bytes_est divided by total generated bytes. Unlike non_residual_buffer_ratio, this excludes TTL-expired bytes.",
    "global_kpi.ue_throughput_jain": "Jain fairness index over per-UE served throughput.",
    "global_kpi.ue_goodput_jain": "Jain fairness index over per-UE goodput.",
    "global_kpi.cell_sum_throughput_jain": "Jain fairness index over per-cell served throughput sums.",
    "global_kpi.ue_throughput_p5_mbps": "5th percentile of per-UE served throughput.",
    "global_kpi.ue_goodput_p5_mbps": "5th percentile of per-UE goodput.",
    "global_kpi.cell_edge_spectral_efficiency_p5_bps_per_hz": "5th-percentile per-UE served throughput divided by the configured carrier bandwidth in Hz. This is a cell-edge spectral-efficiency proxy.",
    "global_kpi.ue_throughput_p10_mbps": "10th percentile of per-UE served throughput.",
    "global_kpi.ue_goodput_p10_mbps": "10th percentile of per-UE goodput.",
    "global_kpi.ue_throughput_p50_mbps": "Median per-UE served throughput.",
    "global_kpi.ue_goodput_p50_mbps": "Median per-UE goodput.",
    "global_kpi.scheduled_ratio_mean": "Mean fraction of TTIs in which each UE was scheduled.",
    "global_kpi.scheduled_ratio_jain": "Jain fairness index over per-UE scheduled ratios.",
    "global_kpi.scheduled_ratio_p5": "5th percentile of per-UE scheduled ratio.",
    "global_kpi.scheduled_ratio_p10": "10th percentile of per-UE scheduled ratio.",
    "global_kpi.scheduled_ratio_p50": "Median per-UE scheduled ratio.",
    "global_kpi.ue_fraction_scheduled_ratio_lt_0p7": "Fraction of UEs whose scheduled_ratio is below 0.7.",
    "global_kpi.queue_delay_p50_ms": "Median of per-UE backlog-based queue_delay_est_ms values; not a packet timestamp median.",
    "global_kpi.queue_delay_p90_ms": "90th percentile of per-UE backlog-based queue_delay_est_ms values.",
    "global_kpi.queue_delay_p95_ms": "95th percentile of per-UE backlog-based queue_delay_est_ms values.",
    "global_kpi.queue_delay_non_zero_p50_ms": "Median of non-zero per-UE backlog-based queue_delay_est_ms values.",
    "global_kpi.queue_delay_non_zero_p95_ms": "95th percentile of non-zero per-UE backlog-based queue_delay_est_ms values.",
    "global_kpi.ue_fraction_queue_delay_gt_10s": "Fraction of UEs whose backlog-based queue_delay_est_ms exceeds 10 seconds.",
    "global_kpi.ue_fraction_queue_delay_gt_20s": "Fraction of UEs whose backlog-based queue_delay_est_ms exceeds 20 seconds.",
    "global_kpi.backlog_free_ue_ratio": "Fraction of UEs with zero residual MAC buffer at the end of the run.",
    "global_kpi.prg_utilization_ratio": "Fraction of available PRG opportunities that were assigned by the scheduler over the whole run, parsed from PRG_UTILIZATION log lines.",
    "global_kpi.packet_delay_served_pkt_count": "Number of fully served packets contributing to packet-level delay statistics.",
    "global_kpi.packet_delay_pending_pkt_count": "Number of packets or fragments still pending in MAC packet queues at the end of the run.",
    "global_kpi.packet_delay_mean_ms": "Mean packet-level delay over all fully served packets.",
    "global_kpi.packet_delay_p50_ms": "Median packet-level delay over all fully served packets.",
    "global_kpi.packet_delay_p90_ms": "90th percentile packet-level delay over all fully served packets.",
    "global_kpi.packet_delay_p95_ms": "95th percentile packet-level delay over all fully served packets.",
    "global_kpi.packet_delay_max_ms": "Maximum packet-level delay over all fully served packets.",
    "global_kpi.ue_count": "Number of UEs included in KPI aggregation.",
    "per_ue_kpi.cell_id": "Serving cell identifier inferred from UE-cell association.",
    "per_ue_kpi.ue_local_id": "UE index within its serving cell.",
    "per_ue_kpi.ue_id": "Global active-UE identifier used in scheduler arrays.",
    "per_ue_kpi.avg_thr_mbps": "Per-UE served throughput estimate over the run, computed from accepted_bytes - flow_queued_bytes - mac_buffer_bytes - expired_bytes divided by simulated time.",
    "per_ue_kpi.goodput_bytes": "Successfully decoded bytes for this UE, accumulated only from transport blocks with tbErr=0.",
    "per_ue_kpi.goodput_mbps": "Per-UE goodput over the run, computed from successfully decoded bytes and simulated time.",
    "per_ue_kpi.avg_mcs_tx_only": "Average selected MCS over TTIs where the UE was actually scheduled.",
    "per_ue_kpi.avg_mcs_all_tti0": "Average selected MCS with unscheduled TTIs counted as zero.",
    "per_ue_kpi.avg_selected_layers_tx_only": "Average selected layer count over TTIs where the UE was actually scheduled.",
    "per_ue_kpi.avg_selected_layers_all_tti": "Average selected layer count with unscheduled TTIs counted as zero.",
    "per_ue_kpi.scheduled_tti_count": "Number of TTIs in which the UE was scheduled.",
    "per_ue_kpi.no_tx_tti_count": "Number of TTIs in which the UE was not scheduled.",
    "per_ue_kpi.scheduled_ratio": "scheduled_tti_count divided by total simulated TTIs.",
    "per_ue_kpi.avg_wb_sinr_db": "Average wideband SINR across all TTIs for the UE.",
    "per_ue_kpi.avg_sched_wb_sinr_db": "Average wideband SINR only over TTIs where the UE was scheduled.",
    "per_ue_kpi.avg_predicted_bler": "Mean predicted BLER over scheduled TTIs.",
    "per_ue_kpi.tb_err_count": "Number of scheduled transport blocks that ended in error.",
    "per_ue_kpi.tb_bler": "Transport-block error rate for this UE.",
    "per_ue_kpi.flow_drop_rate": "Fraction of generated bytes dropped before entering the MAC buffer for this UE.",
    "per_ue_kpi.tx_success_rate": "Fraction of scheduled transport blocks decoded successfully for this UE.",
    "per_ue_kpi.tx_drop_rate": "One minus tx_success_rate for this UE.",
    "per_ue_kpi.tx_total_pkts": "Number of scheduled transport blocks counted as transmissions for this UE.",
    "per_ue_kpi.tx_success_pkts": "Number of scheduled transport blocks decoded successfully for this UE.",
    "per_ue_kpi.queue_delay_est_ms": "Backlog-based end-of-run queueing delay estimate for this UE; not a packet timestamp average.",
    "per_ue_kpi.packet_delay_served_pkt_count": "Number of fully served packets for this UE contributing to packet-level delay statistics.",
    "per_ue_kpi.packet_delay_pending_pkt_count": "Number of packets or fragments still pending for this UE at the end of the run.",
    "per_ue_kpi.packet_delay_mean_ms": "Mean packet-level delay over fully served packets for this UE.",
    "per_ue_kpi.packet_delay_p50_ms": "Median packet-level delay over fully served packets for this UE.",
    "per_ue_kpi.packet_delay_p90_ms": "90th percentile packet-level delay over fully served packets for this UE.",
    "per_ue_kpi.packet_delay_p95_ms": "95th percentile packet-level delay over fully served packets for this UE.",
    "per_ue_kpi.packet_delay_max_ms": "Maximum packet-level delay over fully served packets for this UE.",
    "per_ue_kpi.generated_bytes": "Total generated traffic bytes for this UE.",
    "per_ue_kpi.accepted_bytes": "Total bytes accepted into the flow/MAC pipeline for this UE.",
    "per_ue_kpi.dropped_bytes": "Total generated bytes dropped before reaching the MAC buffer for this UE.",
    "per_ue_kpi.flow_queued_bytes": "Residual bytes still left in the pre-MAC flow queue for this UE at the end of the run.",
    "per_ue_kpi.mac_buffer_bytes": "Residual bytes still left in the MAC buffer for this UE at the end of the run.",
    "per_ue_kpi.mcs_samples": "Number of scheduled-TTI MCS samples contributing to avg_mcs_tx_only.",
    "per_cell_kpi.cell_id": "Serving cell identifier.",
    "per_cell_kpi.ue_count": "Number of UEs aggregated into this cell KPI row.",
    "per_cell_kpi.cell_sum_thr_mbps": "Sum of per-UE served throughput estimates in this cell.",
    "per_cell_kpi.cell_sum_goodput_mbps": "Sum of per-UE goodput values in this cell.",
    "per_cell_kpi.cell_avg_ue_thr_mbps": "Mean per-UE served throughput estimate in this cell.",
    "per_cell_kpi.cell_avg_ue_goodput_mbps": "Mean per-UE goodput in this cell.",
    "per_cell_kpi.cell_avg_mcs_tx_only": "Average selected MCS over scheduled TTIs across UEs in this cell.",
    "per_cell_kpi.cell_avg_mcs_all_tti0": "Average selected MCS with unscheduled TTIs counted as zero across the cell.",
    "per_cell_kpi.cell_scheduled_tti_count": "Sum of scheduled_tti_count across UEs in this cell.",
    "per_cell_kpi.cell_no_tx_tti_count": "Sum of no_tx_tti_count across UEs in this cell.",
    "per_cell_kpi.cell_scheduled_ratio": "cell_scheduled_tti_count divided by total scheduled plus no-tx TTI samples across UEs in this cell.",
    "per_cell_kpi.cell_avg_wb_sinr_db": "Average wideband SINR across all UE-TTI samples in this cell.",
    "per_cell_kpi.cell_avg_sched_wb_sinr_db": "Average wideband SINR over scheduled UE-TTI samples in this cell.",
    "per_cell_kpi.cell_avg_predicted_bler": "Average predicted BLER over scheduled UE-TTI samples in this cell.",
    "per_cell_kpi.cell_tb_err_count": "Sum of transport-block errors across UEs in this cell.",
    "per_cell_kpi.cell_tb_bler": "Transport-block BLER aggregated over this cell.",
    "per_cell_kpi.cell_tx_success_rate": "Transport-block success rate aggregated over this cell.",
    "per_cell_kpi.cell_tx_drop_rate": "One minus cell_tx_success_rate.",
    "per_cell_kpi.cell_tx_total_pkts": "Total counted transport-block transmissions in this cell.",
    "per_cell_kpi.cell_tx_success_pkts": "Total successful transport-block transmissions in this cell.",
    "per_cell_kpi.cell_flow_drop_rate": "Generated-byte drop rate aggregated over this cell.",
    "per_cell_kpi.cell_avg_queue_delay_est_ms": "Mean of per-UE backlog-based queue_delay_est_ms values in this cell.",
    "per_cell_kpi.cell_total_generated_bytes": "Sum of generated_bytes across UEs in this cell.",
    "per_cell_kpi.cell_total_mac_buffer_bytes": "Sum of end-of-run MAC buffer bytes across UEs in this cell.",
    "per_cell_kpi.cell_total_goodput_bytes": "Sum of successfully decoded bytes across UEs in this cell.",
    "per_cell_kpi.cell_total_mcs_samples": "Total MCS samples collected over scheduled TTIs in this cell.",
    "cpu_gpu_compare.instantaneous_mean_mbps_cpu": "Mean CPU-path instantaneous cluster throughput from scheduler arrays.",
    "cpu_gpu_compare.instantaneous_mean_mbps_gpu": "Mean GPU-path instantaneous cluster throughput from scheduler arrays.",
    "cpu_gpu_compare.instantaneous_mean_gpu_minus_cpu_mbps": "GPU instantaneous mean minus CPU instantaneous mean.",
    "cpu_gpu_compare.instantaneous_mean_gpu_over_cpu_ratio": "GPU instantaneous mean divided by CPU instantaneous mean.",
    "cpu_gpu_compare.long_term_sum_mean_mbps_cpu": "Mean CPU-path long-term cluster throughput from scheduler avg-rate arrays.",
    "cpu_gpu_compare.long_term_sum_mean_mbps_gpu": "Mean GPU-path long-term cluster throughput from scheduler avg-rate arrays.",
    "cpu_gpu_compare.long_term_sum_mean_gpu_minus_cpu_mbps": "GPU long-term mean minus CPU long-term mean.",
    "cpu_gpu_compare.long_term_sum_mean_gpu_over_cpu_ratio": "GPU long-term mean divided by CPU long-term mean.",
    "cpu_gpu_compare.long_term_sum_last_mbps_cpu": "Last CPU-path long-term cluster throughput sample.",
    "cpu_gpu_compare.long_term_sum_last_mbps_gpu": "Last GPU-path long-term cluster throughput sample.",
    "cpu_gpu_compare.long_term_sum_last_gpu_minus_cpu_mbps": "GPU last long-term sample minus CPU last long-term sample.",
    "cpu_gpu_compare.long_term_sum_last_gpu_over_cpu_ratio": "GPU last long-term sample divided by CPU last long-term sample.",
    "cpu_gpu_compare.per_ue_avg_mean_mbps_cpu": "Mean CPU-path per-UE avg-rate state from scheduler arrays.",
    "cpu_gpu_compare.per_ue_avg_mean_mbps_gpu": "Mean GPU-path per-UE avg-rate state from scheduler arrays.",
    "cpu_gpu_compare.per_ue_avg_mean_gpu_minus_cpu_mbps": "GPU mean per-UE avg-rate state minus CPU mean.",
    "cpu_gpu_compare.per_ue_avg_mean_gpu_over_cpu_ratio": "GPU mean per-UE avg-rate state divided by CPU mean.",
}

UE_KPI_FIELD_ORDER = [
    "cell_id",
    "ue_local_id",
    "ue_id",
    "avg_thr_mbps",
    "goodput_bytes",
    "goodput_mbps",
    "avg_mcs_tx_only",
    "avg_mcs_all_tti0",
    "avg_selected_layers_tx_only",
    "avg_selected_layers_all_tti",
    "scheduled_tti_count",
    "no_tx_tti_count",
    "scheduled_ratio",
    "avg_wb_sinr_db",
    "avg_sched_wb_sinr_db",
    "avg_predicted_bler",
    "tb_err_count",
    "tb_bler",
    "tx_success_rate",
    "tx_drop_rate",
    "tx_total_pkts",
    "tx_success_pkts",
    "queue_delay_est_ms",
    "packet_delay_served_pkt_count",
    "packet_delay_pending_pkt_count",
    "packet_delay_mean_ms",
    "packet_delay_p50_ms",
    "packet_delay_p90_ms",
    "packet_delay_p95_ms",
    "packet_delay_max_ms",
    "generated_bytes",
    "accepted_bytes",
    "dropped_bytes",
    "flow_queued_bytes",
    "mac_buffer_bytes",
    "mcs_samples",
]

CELL_KPI_FIELD_ORDER = [
    "cell_id",
    "ue_count",
    "cell_sum_thr_mbps",
    "cell_sum_goodput_mbps",
    "cell_avg_ue_thr_mbps",
    "cell_avg_ue_goodput_mbps",
    "cell_avg_mcs_tx_only",
    "cell_avg_mcs_all_tti0",
    "cell_scheduled_tti_count",
    "cell_no_tx_tti_count",
    "cell_scheduled_ratio",
    "cell_avg_wb_sinr_db",
    "cell_avg_sched_wb_sinr_db",
    "cell_avg_predicted_bler",
    "cell_tb_err_count",
    "cell_tb_bler",
    "cell_tx_success_rate",
    "cell_tx_drop_rate",
    "cell_tx_total_pkts",
    "cell_tx_success_pkts",
    "cell_avg_queue_delay_est_ms",
    "cell_total_generated_bytes",
    "cell_total_mac_buffer_bytes",
    "cell_total_goodput_bytes",
    "cell_total_mcs_samples",
]

CPU_GPU_COMPARE_FIELD_ORDER = [
    "instantaneous_mean_mbps_cpu",
    "instantaneous_mean_mbps_gpu",
    "instantaneous_mean_gpu_minus_cpu_mbps",
    "instantaneous_mean_gpu_over_cpu_ratio",
    "long_term_sum_mean_mbps_cpu",
    "long_term_sum_mean_mbps_gpu",
    "long_term_sum_mean_gpu_minus_cpu_mbps",
    "long_term_sum_mean_gpu_over_cpu_ratio",
    "long_term_sum_last_mbps_cpu",
    "long_term_sum_last_mbps_gpu",
    "long_term_sum_last_gpu_minus_cpu_mbps",
    "long_term_sum_last_gpu_over_cpu_ratio",
    "per_ue_avg_mean_mbps_cpu",
    "per_ue_avg_mean_mbps_gpu",
    "per_ue_avg_mean_gpu_minus_cpu_mbps",
    "per_ue_avg_mean_gpu_over_cpu_ratio",
]


def parse_args():
    p = argparse.ArgumentParser(description="Summarize Stage-A MVP KPI from output files.")
    p.add_argument("--output-dir", required=True, help="Run output directory")
    p.add_argument("--slot-duration-ms", type=float, default=0.5, help="Slot duration in ms")
    p.add_argument("--traffic-percent", type=float, default=0.0, help="Traffic UE percentage used in run")
    p.add_argument("--packet-size-bytes", dest="packet_size_bytes", type=float, default=5000.0, help="Traffic packet size in bytes")
    p.add_argument("--traffic-rate", dest="packet_size_bytes", type=float, help=argparse.SUPPRESS)
    p.add_argument("--traffic-arrival-rate", type=float, default=1.0, help="Traffic arrival rate in pkt/TTI")
    p.add_argument("--subcarrier-spacing-hz", type=float, default=30000.0, help="Configured SCS in Hz used to derive bandwidth-based KPI")
    p.add_argument("--prbs-per-group", type=int, default=4, help="Number of PRBs in one PRG/RBG")
    p.add_argument("--prg-count", type=int, default=68, help="Number of PRGs/RBGs per carrier")
    return p.parse_args()


def parse_arrays(text: str):
    pattern = re.compile(r"([A-Za-z0-9_]+)\s*=\s*\[(.*?)\];", re.S)
    parsed = {}
    for key, payload in pattern.findall(text):
        values = []
        for tok in payload.split():
            try:
                values.append(float(tok))
            except ValueError:
                continue
        parsed[key] = values
    return parsed


def pct(values, p):
    if not values:
        return 0.0
    if p <= 0:
        return min(values)
    if p >= 100:
        return max(values)
    arr = sorted(values)
    pos = (len(arr) - 1) * p / 100.0
    lo = int(math.floor(pos))
    hi = int(math.ceil(pos))
    if lo == hi:
        return arr[lo]
    w = pos - lo
    return arr[lo] * (1.0 - w) + arr[hi] * w


def basic_stats(values):
    if not values:
        return {"count": 0, "mean": 0.0, "p5": 0.0, "p50": 0.0, "p95": 0.0, "min": 0.0, "max": 0.0, "last": 0.0}
    return {
        "count": len(values),
        "mean": mean(values),
        "p5": pct(values, 5),
        "p50": pct(values, 50),
        "p95": pct(values, 95),
        "min": min(values),
        "max": max(values),
        "last": values[-1],
    }


def jain_index(values):
    if not values:
        return 0.0
    s = sum(values)
    ss = sum(v * v for v in values)
    if ss <= 0.0:
        return 0.0
    return (s * s) / (len(values) * ss)


def weighted_mean(values, weights):
    total_w = sum(weights)
    if total_w <= 0:
        return 0.0
    return sum(v * w for v, w in zip(values, weights)) / float(total_w)


def parse_traffic_kpi(log_text: str):
    l1 = re.findall(
        r"TRAFFIC_KPI flows=(\d+)\s+generated_pkts=(\d+)\s+generated_bytes=(\d+)\s+accepted_bytes=(\d+)\s+dropped_bytes=(\d+)\s+flow_queued_bytes=(\d+)\s+mac_buffer_bytes=(\d+)\s+served_bytes_est=(\d+)",
        log_text,
    )
    l2 = re.findall(
        r"TRAFFIC_KPI offered_mbps=([0-9eE+\-\.]+)\s+served_mbps_est=([0-9eE+\-\.]+)\s+drop_rate=([0-9eE+\-\.]+)\s+queue_delay_est_ms=([0-9eE+\-\.]+)",
        log_text,
    )
    if not l1 or not l2:
        return None
    a = l1[-1]
    b = l2[-1]
    return {
        "flows": int(a[0]),
        "generated_pkts": int(a[1]),
        "generated_bytes": int(a[2]),
        "accepted_bytes": int(a[3]),
        "dropped_bytes": int(a[4]),
        "flow_queued_bytes": int(a[5]),
        "mac_buffer_bytes": int(a[6]),
        "served_bytes_est": int(a[7]),
        "offered_mbps": float(b[0]),
        "served_mbps_est": float(b[1]),
        "drop_rate": float(b[2]),
        "queue_delay_est_ms": float(b[3]),
    }


def parse_traffic_goodput_kpi(log_text: str):
    matches = re.findall(
        r"TRAFFIC_GOODPUT goodput_bytes=(\d+)\s+goodput_mbps=([0-9eE+\-\.]+)",
        log_text,
    )
    if not matches:
        return None
    m = matches[-1]
    return {
        "goodput_bytes": int(m[0]),
        "goodput_mbps": float(m[1]),
    }


def parse_traffic_expiry_kpi(log_text: str):
    matches = re.findall(
        r"TRAFFIC_EXPIRY expired_bytes=(\d+)\s+expired_packets=(\d+)\s+expiry_drop_rate=([0-9eE+\-\.]+)",
        log_text,
    )
    if not matches:
        return None
    m = matches[-1]
    return {
        "expired_bytes": int(m[0]),
        "expired_packets": int(m[1]),
        "expiry_drop_rate": float(m[2]),
    }


def parse_traffic_packet_delay_kpi(log_text: str):
    matches = re.findall(
        r"TRAFFIC_PKT_DELAY served_pkt_count=(\d+)\s+pending_pkt_count=(\d+)\s+mean_ms=([0-9eE+\-\.]+)\s+p50_ms=([0-9eE+\-\.]+)\s+p90_ms=([0-9eE+\-\.]+)\s+p95_ms=([0-9eE+\-\.]+)\s+max_ms=([0-9eE+\-\.]+)",
        log_text,
    )
    if not matches:
        return None
    m = matches[-1]
    return {
        "packet_delay_served_pkt_count": int(m[0]),
        "packet_delay_pending_pkt_count": int(m[1]),
        "packet_delay_mean_ms": float(m[2]),
        "packet_delay_p50_ms": float(m[3]),
        "packet_delay_p90_ms": float(m[4]),
        "packet_delay_p95_ms": float(m[5]),
        "packet_delay_max_ms": float(m[6]),
    }


def parse_prg_utilization_kpi(log_text: str):
    matches = re.findall(
        r"PRG_UTILIZATION allocated_prg_count=(\d+)\s+total_prg_capacity=(\d+)\s+utilization_ratio=([0-9eE+\-\.]+)",
        log_text,
    )
    if not matches:
        return None
    m = matches[-1]
    return {
        "allocated_prg_count": int(m[0]),
        "total_prg_capacity": int(m[1]),
        "utilization_ratio": float(m[2]),
    }


def parse_ue_kpi(log_text: str):
    pat_new_layers = re.compile(
        r"UE_KPI\s+cell_id=(-?\d+)\s+ue_local_id=(-?\d+)\s+ue_id=(\d+)\s+avg_thr_mbps=([0-9eE+\-\.]+)\s+avg_mcs_tx_only=([0-9eE+\-\.]+)\s+avg_mcs_all_tti0=([0-9eE+\-\.]+)\s+avg_selected_layers_tx_only=([0-9eE+\-\.]+)\s+avg_selected_layers_all_tti=([0-9eE+\-\.]+)\s+scheduled_tti_count=(\d+)\s+no_tx_tti_count=(\d+)\s+scheduled_ratio=([0-9eE+\-\.]+)\s+avg_wb_sinr_db=([0-9eE+\-\.]+)\s+avg_sched_wb_sinr_db=([0-9eE+\-\.]+)\s+avg_predicted_bler=([0-9eE+\-\.]+)\s+tb_err_count=(\d+)\s+tb_bler=([0-9eE+\-\.]+)\s+flow_drop_rate=([0-9eE+\-\.]+)\s+tx_success_rate=([0-9eE+\-\.]+)\s+tx_drop_rate=([0-9eE+\-\.]+)\s+tx_total_pkts=(\d+)\s+tx_success_pkts=(\d+)\s+queue_delay_est_ms=([0-9eE+\-\.]+)\s+generated_bytes=(\d+)\s+accepted_bytes=(\d+)\s+dropped_bytes=(\d+)\s+flow_queued_bytes=(\d+)\s+mac_buffer_bytes=(\d+)\s+mcs_samples=(\d+)"
    )
    pat_new = re.compile(
        r"UE_KPI\s+cell_id=(-?\d+)\s+ue_local_id=(-?\d+)\s+ue_id=(\d+)\s+avg_thr_mbps=([0-9eE+\-\.]+)\s+avg_mcs_tx_only=([0-9eE+\-\.]+)\s+avg_mcs_all_tti0=([0-9eE+\-\.]+)\s+scheduled_tti_count=(\d+)\s+no_tx_tti_count=(\d+)\s+scheduled_ratio=([0-9eE+\-\.]+)\s+avg_wb_sinr_db=([0-9eE+\-\.]+)\s+avg_sched_wb_sinr_db=([0-9eE+\-\.]+)\s+avg_predicted_bler=([0-9eE+\-\.]+)\s+tb_err_count=(\d+)\s+tb_bler=([0-9eE+\-\.]+)\s+flow_drop_rate=([0-9eE+\-\.]+)\s+tx_success_rate=([0-9eE+\-\.]+)\s+tx_drop_rate=([0-9eE+\-\.]+)\s+tx_total_pkts=(\d+)\s+tx_success_pkts=(\d+)\s+queue_delay_est_ms=([0-9eE+\-\.]+)\s+generated_bytes=(\d+)\s+accepted_bytes=(\d+)\s+dropped_bytes=(\d+)\s+flow_queued_bytes=(\d+)\s+mac_buffer_bytes=(\d+)\s+mcs_samples=(\d+)"
    )
    pat_legacy = re.compile(
        r"UE_KPI\s+ue_id=(\d+)\s+avg_thr_mbps=([0-9eE+\-\.]+)\s+avg_mcs=([0-9eE+\-\.]+)\s+drop_rate=([0-9eE+\-\.]+)\s+queue_delay_est_ms=([0-9eE+\-\.]+)\s+generated_bytes=(\d+)\s+accepted_bytes=(\d+)\s+dropped_bytes=(\d+)\s+flow_queued_bytes=(\d+)\s+mac_buffer_bytes=(\d+)\s+mcs_samples=(\d+)"
    )
    rows = []
    for m in pat_new_layers.finditer(log_text):
        rows.append(
            {
                "cell_id": int(m.group(1)),
                "ue_local_id": int(m.group(2)),
                "ue_id": int(m.group(3)),
                "avg_thr_mbps": float(m.group(4)),
                "avg_mcs_tx_only": float(m.group(5)),
                "avg_mcs_all_tti0": float(m.group(6)),
                "avg_selected_layers_tx_only": float(m.group(7)),
                "avg_selected_layers_all_tti": float(m.group(8)),
                "scheduled_tti_count": int(m.group(9)),
                "no_tx_tti_count": int(m.group(10)),
                "scheduled_ratio": float(m.group(11)),
                "avg_wb_sinr_db": float(m.group(12)),
                "avg_sched_wb_sinr_db": float(m.group(13)),
                "avg_predicted_bler": float(m.group(14)),
                "tb_err_count": int(m.group(15)),
                "tb_bler": float(m.group(16)),
                "flow_drop_rate": float(m.group(17)),
                "drop_rate": float(m.group(17)),
                "tx_success_rate": float(m.group(18)),
                "tx_drop_rate": float(m.group(19)),
                "tx_total_pkts": int(m.group(20)),
                "tx_success_pkts": int(m.group(21)),
                "queue_delay_est_ms": float(m.group(22)),
                "generated_bytes": int(m.group(23)),
                "accepted_bytes": int(m.group(24)),
                "dropped_bytes": int(m.group(25)),
                "flow_queued_bytes": int(m.group(26)),
                "mac_buffer_bytes": int(m.group(27)),
                "mcs_samples": int(m.group(28)),
                "avg_mcs": float(m.group(5)),
            }
        )
    if not rows:
        for m in pat_new.finditer(log_text):
            scheduled_tti_count = int(m.group(7))
            scheduled_ratio = float(m.group(9))
            avg_selected_layers_tx_only = 1.0 if scheduled_tti_count > 0 else -1.0
            avg_selected_layers_all_tti = scheduled_ratio if scheduled_tti_count > 0 else 0.0
            rows.append(
                {
                    "cell_id": int(m.group(1)),
                    "ue_local_id": int(m.group(2)),
                    "ue_id": int(m.group(3)),
                    "avg_thr_mbps": float(m.group(4)),
                    "avg_mcs_tx_only": float(m.group(5)),
                    "avg_mcs_all_tti0": float(m.group(6)),
                    "avg_selected_layers_tx_only": avg_selected_layers_tx_only,
                    "avg_selected_layers_all_tti": avg_selected_layers_all_tti,
                    "scheduled_tti_count": scheduled_tti_count,
                    "no_tx_tti_count": int(m.group(8)),
                    "scheduled_ratio": scheduled_ratio,
                    "avg_wb_sinr_db": float(m.group(10)),
                    "avg_sched_wb_sinr_db": float(m.group(11)),
                    "avg_predicted_bler": float(m.group(12)),
                    "tb_err_count": int(m.group(13)),
                    "tb_bler": float(m.group(14)),
                    "flow_drop_rate": float(m.group(15)),
                    "drop_rate": float(m.group(15)),
                    "tx_success_rate": float(m.group(16)),
                    "tx_drop_rate": float(m.group(17)),
                    "tx_total_pkts": int(m.group(18)),
                    "tx_success_pkts": int(m.group(19)),
                    "queue_delay_est_ms": float(m.group(20)),
                    "generated_bytes": int(m.group(21)),
                    "accepted_bytes": int(m.group(22)),
                    "dropped_bytes": int(m.group(23)),
                    "flow_queued_bytes": int(m.group(24)),
                    "mac_buffer_bytes": int(m.group(25)),
                    "mcs_samples": int(m.group(26)),
                    "avg_mcs": float(m.group(5)),
                }
            )
    if not rows:
        for m in pat_legacy.finditer(log_text):
            ue_id = int(m.group(1))
            rows.append(
                {
                    "cell_id": -1,
                    "ue_local_id": ue_id,
                    "ue_id": ue_id,
                    "avg_thr_mbps": float(m.group(2)),
                    "avg_mcs_tx_only": float(m.group(3)),
                    "avg_mcs_all_tti0": float(m.group(3)),
                    "avg_selected_layers_tx_only": 1.0 if int(m.group(11)) > 0 else -1.0,
                    "avg_selected_layers_all_tti": 1.0 if int(m.group(11)) > 0 else 0.0,
                    "avg_mcs": float(m.group(3)),
                    "scheduled_tti_count": int(m.group(11)),
                    "no_tx_tti_count": 0,
                    "scheduled_ratio": 1.0,
                    "avg_wb_sinr_db": 0.0,
                    "avg_sched_wb_sinr_db": 0.0,
                    "avg_predicted_bler": 0.0,
                    "tb_err_count": 0,
                    "tb_bler": 0.0,
                    "flow_drop_rate": float(m.group(4)),
                    "drop_rate": float(m.group(4)),
                    "tx_success_rate": 0.0,
                    "tx_drop_rate": 0.0,
                    "tx_total_pkts": 0,
                    "tx_success_pkts": 0,
                    "queue_delay_est_ms": float(m.group(5)),
                    "generated_bytes": int(m.group(6)),
                    "accepted_bytes": int(m.group(7)),
                    "dropped_bytes": int(m.group(8)),
                    "flow_queued_bytes": int(m.group(9)),
                    "mac_buffer_bytes": int(m.group(10)),
                    "mcs_samples": int(m.group(11)),
                }
            )
    rows.sort(key=lambda x: (x["cell_id"], x["ue_local_id"], x["ue_id"]))
    return rows


def parse_ue_packet_delay_kpi(log_text: str):
    pat = re.compile(
        r"UE_PKT_DELAY\s+ue_id=(\d+)\s+served_pkt_count=(\d+)\s+pending_pkt_count=(\d+)\s+packet_delay_mean_ms=([0-9eE+\-\.]+)\s+packet_delay_p50_ms=([0-9eE+\-\.]+)\s+packet_delay_p90_ms=([0-9eE+\-\.]+)\s+packet_delay_p95_ms=([0-9eE+\-\.]+)\s+packet_delay_max_ms=([0-9eE+\-\.]+)"
    )
    rows = {}
    for m in pat.finditer(log_text):
        rows[int(m.group(1))] = {
            "packet_delay_served_pkt_count": int(m.group(2)),
            "packet_delay_pending_pkt_count": int(m.group(3)),
            "packet_delay_mean_ms": float(m.group(4)),
            "packet_delay_p50_ms": float(m.group(5)),
            "packet_delay_p90_ms": float(m.group(6)),
            "packet_delay_p95_ms": float(m.group(7)),
            "packet_delay_max_ms": float(m.group(8)),
        }
    return rows


def parse_ue_goodput_kpi(log_text: str):
    pat = re.compile(
        r"UE_GOODPUT\s+ue_id=(\d+)\s+goodput_bytes=(\d+)\s+goodput_mbps=([0-9eE+\-\.]+)"
    )
    rows = {}
    for m in pat.finditer(log_text):
        rows[int(m.group(1))] = {
            "goodput_bytes": int(m.group(2)),
            "goodput_mbps": float(m.group(3)),
        }
    return rows


def merge_ue_goodput(ue_kpi, ue_goodput):
    for row in ue_kpi:
        gp = ue_goodput.get(row["ue_id"], {})
        row["goodput_bytes"] = gp.get("goodput_bytes")
        row["goodput_mbps"] = gp.get("goodput_mbps")
    return ue_kpi


def merge_ue_packet_delay(ue_kpi, ue_packet_delay):
    for row in ue_kpi:
        pkt = ue_packet_delay.get(row["ue_id"], {})
        row["packet_delay_served_pkt_count"] = pkt.get("packet_delay_served_pkt_count", 0)
        row["packet_delay_pending_pkt_count"] = pkt.get("packet_delay_pending_pkt_count", 0)
        row["packet_delay_mean_ms"] = pkt.get("packet_delay_mean_ms", 0.0)
        row["packet_delay_p50_ms"] = pkt.get("packet_delay_p50_ms", 0.0)
        row["packet_delay_p90_ms"] = pkt.get("packet_delay_p90_ms", 0.0)
        row["packet_delay_p95_ms"] = pkt.get("packet_delay_p95_ms", 0.0)
        row["packet_delay_max_ms"] = pkt.get("packet_delay_max_ms", 0.0)
    return ue_kpi


def summarize_cell_kpi(ue_kpi):
    groups = {}
    for row in ue_kpi:
        cell_id = row.get("cell_id", -1)
        groups.setdefault(cell_id, []).append(row)

    rows = []
    for cell_id in sorted(groups):
        cell_rows = groups[cell_id]
        ue_count = len(cell_rows)
        thr_values = [r["avg_thr_mbps"] for r in cell_rows]
        goodput_values = [r.get("goodput_mbps") for r in cell_rows if r.get("goodput_mbps") is not None]
        delay_values = [r["queue_delay_est_ms"] for r in cell_rows]
        total_mcs_samples = sum(r.get("mcs_samples", 0) for r in cell_rows)
        total_tx_pkts = sum(r.get("tx_total_pkts", 0) for r in cell_rows)
        total_tx_success = sum(r.get("tx_success_pkts", 0) for r in cell_rows)
        total_tb_err = sum(r.get("tb_err_count", 0) for r in cell_rows)
        total_generated = sum(r.get("generated_bytes", 0) for r in cell_rows)
        total_mac_buffer = sum(r.get("mac_buffer_bytes", 0) for r in cell_rows)
        total_goodput_bytes = (
            sum(r.get("goodput_bytes", 0) for r in cell_rows if r.get("goodput_bytes") is not None)
            if any(r.get("goodput_bytes") is not None for r in cell_rows)
            else None
        )
        total_flow_drop_num = sum(r.get("dropped_bytes", 0) for r in cell_rows)
        total_sched_tti = sum(r.get("scheduled_tti_count", r.get("mcs_samples", 0)) for r in cell_rows)
        total_no_tx_tti = sum(r.get("no_tx_tti_count", 0) for r in cell_rows)
        avg_mcs_num = sum(r.get("avg_mcs_tx_only", r.get("avg_mcs", 0.0)) * r.get("mcs_samples", 0) for r in cell_rows)
        avg_mcs_all_tti0_num = sum(r.get("avg_mcs_all_tti0", r.get("avg_mcs", 0.0)) * (r.get("scheduled_tti_count", r.get("mcs_samples", 0)) + r.get("no_tx_tti_count", 0)) for r in cell_rows)
        avg_sinr_num = sum(r.get("avg_wb_sinr_db", 0.0) * max(r.get("scheduled_tti_count", 0) + r.get("no_tx_tti_count", 0), 1) for r in cell_rows)
        avg_sched_sinr_num = sum(r.get("avg_sched_wb_sinr_db", 0.0) * max(r.get("scheduled_tti_count", r.get("mcs_samples", 0)), 1) for r in cell_rows)
        avg_pred_bler_num = sum(r.get("avg_predicted_bler", 0.0) * max(r.get("scheduled_tti_count", r.get("mcs_samples", 0)), 1) for r in cell_rows)
        total_tti_samples = sum(r.get("scheduled_tti_count", r.get("mcs_samples", 0)) + r.get("no_tx_tti_count", 0) for r in cell_rows)
        cell_tx_success_rate = float(total_tx_success) / float(total_tx_pkts) if total_tx_pkts > 0 else 0.0
        cell_flow_drop_rate = float(total_flow_drop_num) / float(total_generated) if total_generated > 0 else 0.0

        rows.append(
            {
                "cell_id": cell_id,
                "ue_count": ue_count,
                "cell_sum_thr_mbps": sum(thr_values),
                "cell_sum_goodput_mbps": sum(goodput_values) if goodput_values else None,
                "cell_avg_ue_thr_mbps": mean(thr_values) if thr_values else 0.0,
                "cell_avg_ue_goodput_mbps": mean(goodput_values) if goodput_values else None,
                "cell_avg_mcs_tx_only": avg_mcs_num / total_mcs_samples if total_mcs_samples > 0 else 0.0,
                "cell_avg_mcs_all_tti0": avg_mcs_all_tti0_num / total_tti_samples if total_tti_samples > 0 else 0.0,
                "cell_scheduled_tti_count": total_sched_tti,
                "cell_no_tx_tti_count": total_no_tx_tti,
                "cell_scheduled_ratio": float(total_sched_tti) / float(total_sched_tti + total_no_tx_tti) if (total_sched_tti + total_no_tx_tti) > 0 else 0.0,
                "cell_avg_wb_sinr_db": avg_sinr_num / total_tti_samples if total_tti_samples > 0 else 0.0,
                "cell_avg_sched_wb_sinr_db": avg_sched_sinr_num / total_sched_tti if total_sched_tti > 0 else 0.0,
                "cell_avg_predicted_bler": avg_pred_bler_num / total_sched_tti if total_sched_tti > 0 else 0.0,
                "cell_tb_err_count": total_tb_err,
                "cell_tb_bler": float(total_tb_err) / float(total_tx_pkts) if total_tx_pkts > 0 else 0.0,
                "cell_tx_success_rate": cell_tx_success_rate,
                "cell_tx_drop_rate": 1.0 - cell_tx_success_rate if total_tx_pkts > 0 else 0.0,
                "cell_tx_total_pkts": total_tx_pkts,
                "cell_tx_success_pkts": total_tx_success,
                "cell_flow_drop_rate": cell_flow_drop_rate,
                "cell_avg_queue_delay_est_ms": mean(delay_values) if delay_values else 0.0,
                "cell_total_generated_bytes": total_generated,
                "cell_total_mac_buffer_bytes": total_mac_buffer,
                "cell_total_goodput_bytes": total_goodput_bytes,
                "cell_total_mcs_samples": total_mcs_samples,
            }
        )
    return rows


def summarize_global_kpi(ue_kpi, cell_kpi, traffic_kpi=None, bandwidth_hz=None, prg_kpi=None):
    thr_values = [float(r.get("avg_thr_mbps", 0.0)) for r in ue_kpi]
    goodput_present = all(r.get("goodput_mbps") is not None for r in ue_kpi) if ue_kpi else False
    goodput_values = [float(r.get("goodput_mbps", 0.0)) for r in ue_kpi] if goodput_present else []
    sched_values = [float(r.get("scheduled_ratio", 0.0)) for r in ue_kpi]
    queue_delay_values = [float(r.get("queue_delay_est_ms", 0.0)) for r in ue_kpi]
    queue_delay_non_zero_values = [v for v in queue_delay_values if v > 0.0]
    generated_values = [int(r.get("generated_bytes", 0)) for r in ue_kpi]
    mac_buffer_values = [int(r.get("mac_buffer_bytes", 0)) for r in ue_kpi]
    tx_total_pkts_values = [int(r.get("tx_total_pkts", 0)) for r in ue_kpi]
    tx_success_pkts_values = [int(r.get("tx_success_pkts", 0)) for r in ue_kpi]
    tb_err_count_values = [int(r.get("tb_err_count", 0)) for r in ue_kpi]
    predicted_bler_values = [float(r.get("avg_predicted_bler", 0.0)) for r in ue_kpi]
    predicted_bler_weights = [max(int(r.get("scheduled_tti_count", r.get("mcs_samples", 0))), 0) for r in ue_kpi]
    cell_thr_values = [float(r.get("cell_sum_thr_mbps", 0.0)) for r in cell_kpi]

    ue_count = len(ue_kpi)
    total_generated_bytes = sum(generated_values)
    total_expired_bytes = int((traffic_kpi or {}).get("expired_bytes", 0) or 0)
    total_expired_packets = int((traffic_kpi or {}).get("expired_packets", 0) or 0)
    total_mac_buffer_bytes = sum(mac_buffer_values)
    served_bytes_est = int((traffic_kpi or {}).get("served_bytes_est", 0) or 0)
    total_tx_total_pkts = sum(tx_total_pkts_values)
    total_tx_success_pkts = sum(tx_success_pkts_values)
    total_tb_err_count = sum(tb_err_count_values)

    residual_buffer_ratio = float(total_mac_buffer_bytes) / float(total_generated_bytes) if total_generated_bytes > 0 else 0.0
    non_residual_buffer_ratio = 1.0 - residual_buffer_ratio if total_generated_bytes > 0 else 0.0
    served_buffer_ratio = (
        float(served_bytes_est) / float(total_generated_bytes) if total_generated_bytes > 0 and served_bytes_est > 0 else 0.0
    )
    if total_generated_bytes > 0 and served_bytes_est <= 0 and traffic_kpi is None:
        served_buffer_ratio = non_residual_buffer_ratio
    backlog_free_ue_ratio = (
        float(sum(1 for x in mac_buffer_values if x <= 0)) / float(ue_count) if ue_count > 0 else 0.0
    )

    cluster_sum_throughput_mbps = sum(thr_values)
    if traffic_kpi is not None and traffic_kpi.get("served_mbps_est") is not None:
        cluster_sum_throughput_mbps = float(traffic_kpi["served_mbps_est"])
    cluster_goodput_mbps = None
    if traffic_kpi is not None and traffic_kpi.get("goodput_mbps") is not None:
        cluster_goodput_mbps = float(traffic_kpi["goodput_mbps"])
    elif goodput_present:
        cluster_goodput_mbps = sum(goodput_values)
    average_ue_throughput_mbps = cluster_sum_throughput_mbps / float(ue_count) if ue_count > 0 else 0.0
    average_ue_goodput_mbps = cluster_goodput_mbps / float(ue_count) if ue_count > 0 and cluster_goodput_mbps is not None else None
    ue_throughput_p5_mbps = pct(thr_values, 5)
    cluster_spectral_efficiency_bps_per_hz = (
        (cluster_sum_throughput_mbps * 1.0e6) / float(bandwidth_hz) if bandwidth_hz and bandwidth_hz > 0.0 else 0.0
    )
    cell_edge_spectral_efficiency_p5_bps_per_hz = (
        (ue_throughput_p5_mbps * 1.0e6) / float(bandwidth_hz) if bandwidth_hz and bandwidth_hz > 0.0 else 0.0
    )

    return {
        "cluster_sum_throughput_mbps": cluster_sum_throughput_mbps,
        "cluster_goodput_mbps": cluster_goodput_mbps,
        "cluster_spectral_efficiency_bps_per_hz": cluster_spectral_efficiency_bps_per_hz,
        "average_ue_throughput_mbps": average_ue_throughput_mbps,
        "average_ue_goodput_mbps": average_ue_goodput_mbps,
        "global_tb_bler": float(total_tb_err_count) / float(total_tx_total_pkts) if total_tx_total_pkts > 0 else 0.0,
        "global_predicted_bler_weighted": weighted_mean(predicted_bler_values, predicted_bler_weights),
        "global_tx_success_rate": float(total_tx_success_pkts) / float(total_tx_total_pkts) if total_tx_total_pkts > 0 else 0.0,
        "total_generated_bytes": total_generated_bytes,
        "total_expired_bytes": total_expired_bytes,
        "total_expired_packets": total_expired_packets,
        "expiry_drop_rate": float((traffic_kpi or {}).get("expiry_drop_rate", 0.0) or 0.0),
        "total_mac_buffer_bytes": total_mac_buffer_bytes,
        "residual_buffer_ratio": residual_buffer_ratio,
        "non_residual_buffer_ratio": non_residual_buffer_ratio,
        "served_buffer_ratio": served_buffer_ratio,
        "ue_throughput_jain": jain_index(thr_values),
        "ue_goodput_jain": jain_index(goodput_values) if goodput_present else None,
        "cell_sum_throughput_jain": jain_index(cell_thr_values),
        "ue_throughput_p5_mbps": ue_throughput_p5_mbps,
        "ue_goodput_p5_mbps": pct(goodput_values, 5) if goodput_present else None,
        "cell_edge_spectral_efficiency_p5_bps_per_hz": cell_edge_spectral_efficiency_p5_bps_per_hz,
        "ue_throughput_p10_mbps": pct(thr_values, 10),
        "ue_goodput_p10_mbps": pct(goodput_values, 10) if goodput_present else None,
        "ue_throughput_p50_mbps": pct(thr_values, 50),
        "ue_goodput_p50_mbps": pct(goodput_values, 50) if goodput_present else None,
        "scheduled_ratio_mean": mean(sched_values) if sched_values else 0.0,
        "scheduled_ratio_jain": jain_index(sched_values),
        "scheduled_ratio_p5": pct(sched_values, 5),
        "scheduled_ratio_p10": pct(sched_values, 10),
        "scheduled_ratio_p50": pct(sched_values, 50),
        "ue_fraction_scheduled_ratio_lt_0p7": (
            float(sum(1 for v in sched_values if v < 0.7)) / float(len(sched_values)) if sched_values else 0.0
        ),
        "queue_delay_p50_ms": pct(queue_delay_values, 50),
        "queue_delay_p90_ms": pct(queue_delay_values, 90),
        "queue_delay_p95_ms": pct(queue_delay_values, 95),
        "queue_delay_non_zero_p50_ms": pct(queue_delay_non_zero_values, 50),
        "queue_delay_non_zero_p95_ms": pct(queue_delay_non_zero_values, 95),
        "ue_fraction_queue_delay_gt_10s": (
            float(sum(1 for v in queue_delay_values if v > 10000.0)) / float(len(queue_delay_values))
            if queue_delay_values
            else 0.0
        ),
        "ue_fraction_queue_delay_gt_20s": (
            float(sum(1 for v in queue_delay_values if v > 20000.0)) / float(len(queue_delay_values))
            if queue_delay_values
            else 0.0
        ),
        "backlog_free_ue_ratio": backlog_free_ue_ratio,
        "prg_utilization_ratio": None if prg_kpi is None else float(prg_kpi.get("utilization_ratio", 0.0)),
        "packet_delay_served_pkt_count": int((traffic_kpi or {}).get("packet_delay_served_pkt_count", 0) or 0),
        "packet_delay_pending_pkt_count": int((traffic_kpi or {}).get("packet_delay_pending_pkt_count", 0) or 0),
        "packet_delay_mean_ms": float((traffic_kpi or {}).get("packet_delay_mean_ms", 0.0) or 0.0),
        "packet_delay_p50_ms": float((traffic_kpi or {}).get("packet_delay_p50_ms", 0.0) or 0.0),
        "packet_delay_p90_ms": float((traffic_kpi or {}).get("packet_delay_p90_ms", 0.0) or 0.0),
        "packet_delay_p95_ms": float((traffic_kpi or {}).get("packet_delay_p95_ms", 0.0) or 0.0),
        "packet_delay_max_ms": float((traffic_kpi or {}).get("packet_delay_max_ms", 0.0) or 0.0),
        "ue_count": ue_count,
    }


def format_metric_value(v):
    if v is None:
        return "N/A"
    if isinstance(v, float):
        return f"{v:.10f}"
    return str(v)


def metric_note(path):
    return METRIC_DEFINITIONS.get(path, "")


def format_metric_line(path, value):
    line = f"{path}: {value}"
    note = metric_note(path)
    if note:
        line += f" | {note}"
    return line


def append_definition_rows(lines, scope, fields):
    for field in fields:
        lines.append(f"{scope},{field},{metric_note(f'{scope}.{field}')}")


def first_present_array(parsed, *keys):
    for key in keys:
        if key in parsed:
            return parsed[key]
    return []


def safe_ratio(num, den):
    if den is None or abs(den) <= 1.0e-12:
        return None
    return num / den


def configured_bandwidth_hz(args):
    prbs_per_group = max(int(args.prbs_per_group), 0)
    prg_count = max(int(args.prg_count), 0)
    scs_hz = max(float(args.subcarrier_spacing_hz), 0.0)
    return 12.0 * scs_hz * float(prbs_per_group) * float(prg_count)


def parse_execution_mode(log_text: str):
    m = re.findall(r"cuMAC scheduler pipeline test: execution mode=([A-Za-z0-9_\-]+)", log_text)
    if not m:
        return "both"
    return m[-1].strip().lower()


def build_cpu_gpu_compare(throughput_summary, execution_mode="both"):
    cpu_long = throughput_summary.get("long_term_sum_mbps_cpu", basic_stats([]))
    gpu_long = throughput_summary.get("long_term_sum_mbps_gpu", basic_stats([]))
    cpu_ins = throughput_summary.get("instantaneous_mbps_cpu", basic_stats([]))
    gpu_ins = throughput_summary.get("instantaneous_mbps_gpu", basic_stats([]))
    cpu_ue = throughput_summary.get("per_ue_avg_mbps_cpu", basic_stats([]))
    gpu_ue = throughput_summary.get("per_ue_avg_mbps_gpu", basic_stats([]))

    compare = {
        "instantaneous_mean_mbps_cpu": cpu_ins["mean"],
        "instantaneous_mean_mbps_gpu": gpu_ins["mean"],
        "instantaneous_mean_gpu_minus_cpu_mbps": gpu_ins["mean"] - cpu_ins["mean"],
        "instantaneous_mean_gpu_over_cpu_ratio": safe_ratio(gpu_ins["mean"], cpu_ins["mean"]),
        "long_term_sum_mean_mbps_cpu": cpu_long["mean"],
        "long_term_sum_mean_mbps_gpu": gpu_long["mean"],
        "long_term_sum_mean_gpu_minus_cpu_mbps": gpu_long["mean"] - cpu_long["mean"],
        "long_term_sum_mean_gpu_over_cpu_ratio": safe_ratio(gpu_long["mean"], cpu_long["mean"]),
        "long_term_sum_last_mbps_cpu": cpu_long["last"],
        "long_term_sum_last_mbps_gpu": gpu_long["last"],
        "long_term_sum_last_gpu_minus_cpu_mbps": gpu_long["last"] - cpu_long["last"],
        "long_term_sum_last_gpu_over_cpu_ratio": safe_ratio(gpu_long["last"], cpu_long["last"]),
        "per_ue_avg_mean_mbps_cpu": cpu_ue["mean"],
        "per_ue_avg_mean_mbps_gpu": gpu_ue["mean"],
        "per_ue_avg_mean_gpu_minus_cpu_mbps": gpu_ue["mean"] - cpu_ue["mean"],
        "per_ue_avg_mean_gpu_over_cpu_ratio": safe_ratio(gpu_ue["mean"], cpu_ue["mean"]),
    }
    if execution_mode == "gpu":
        compare["disabled_in_gpu_only"] = True
        compare["disabled_reason"] = (
            "gpu-only mode disables the independent CPU reference scheduler path; "
            "CPU-side throughput arrays are shadow/replay bookkeeping and should not be interpreted as a baseline comparison."
        )
    else:
        compare["disabled_in_gpu_only"] = False
    return compare


def main():
    args = parse_args()
    out_dir = Path(args.output_dir)
    output_short = out_dir / "output_short.txt"
    output_full = out_dir / "output.txt"
    run_log = out_dir / "run.log"
    summary_json = out_dir / "kpi_summary.json"
    bandwidth_hz = configured_bandwidth_hz(args)

    source_file = output_short if output_short.exists() else output_full
    existing = None
    if source_file.exists():
        arrays = parse_arrays(source_file.read_text())
        log_text = run_log.read_text() if run_log.exists() else ""
        execution_mode = parse_execution_mode(log_text)

        sum_ins_cpu = first_present_array(arrays, "mcType1SumInsThrRecordsCpu", "mcType0SumInsThrRecordsCpu")
        sum_ins_gpu = first_present_array(arrays, "mcType1SumInsThrRecordsGpu", "mcType0SumInsThrRecordsGpu")
        sum_cell_cpu = first_present_array(arrays, "mcType1SumCellThrRecordsCpu", "mcType0SumCellThrRecordsCpu")
        sum_cell_gpu = first_present_array(arrays, "mcType1SumCellThrRecordsGpu", "mcType0SumCellThrRecordsGpu")
        ue_avg_cpu = first_present_array(arrays, "mcType1AvgRatesCpu", "mcType0AvgRatesCpu")
        ue_avg_gpu = first_present_array(arrays, "mcType1AvgRatesGpu", "mcType0AvgRatesGpu")

        throughput_ins_mbps = [x / 1e6 for x in sum_ins_gpu]
        throughput_cell_mbps = [x / 1e6 for x in sum_cell_gpu]
        ue_avg_mbps = [x / 1e6 for x in ue_avg_gpu]

        traffic_kpi = parse_traffic_kpi(log_text)
        traffic_goodput_kpi = parse_traffic_goodput_kpi(log_text)
        traffic_expiry_kpi = parse_traffic_expiry_kpi(log_text)
        traffic_packet_delay_kpi = parse_traffic_packet_delay_kpi(log_text)
        prg_kpi = parse_prg_utilization_kpi(log_text)
        if traffic_kpi is not None and traffic_goodput_kpi is not None:
            traffic_kpi.update(traffic_goodput_kpi)
        if traffic_kpi is not None and traffic_expiry_kpi is not None:
            traffic_kpi.update(traffic_expiry_kpi)
        if traffic_kpi is not None and traffic_packet_delay_kpi is not None:
            traffic_kpi.update(traffic_packet_delay_kpi)
        ue_kpi = parse_ue_kpi(log_text)
        ue_kpi = merge_ue_goodput(ue_kpi, parse_ue_goodput_kpi(log_text))
        ue_kpi = merge_ue_packet_delay(ue_kpi, parse_ue_packet_delay_kpi(log_text))
        throughput_summary = {
            "instantaneous_mbps_cpu": basic_stats([x / 1e6 for x in sum_ins_cpu]),
            "instantaneous_mbps_gpu": basic_stats(throughput_ins_mbps),
            "long_term_sum_mbps_cpu": basic_stats([x / 1e6 for x in sum_cell_cpu]),
            "long_term_sum_mbps_gpu": basic_stats(throughput_cell_mbps),
            "per_ue_avg_mbps_cpu": basic_stats([x / 1e6 for x in ue_avg_cpu]),
            "per_ue_avg_mbps_gpu": basic_stats(ue_avg_mbps),
        }
    elif summary_json.exists():
        existing = json.loads(summary_json.read_text())
        execution_mode = existing.get("execution_mode", "both")
        sum_ins_cpu = []
        sum_ins_gpu = []
        sum_cell_cpu = []
        sum_cell_gpu = []
        ue_avg_cpu = []
        ue_avg_gpu = []
        throughput_ins_mbps = []
        throughput_cell_mbps = []
        ue_avg_mbps = []
        traffic_kpi = existing.get("traffic")
        prg_kpi = existing.get("prg_utilization")
        ue_kpi = existing.get("per_ue_kpi", [])
        throughput_summary = existing.get("throughput", {})
        throughput_summary.setdefault("instantaneous_mbps_cpu", basic_stats([]))
        throughput_summary.setdefault("instantaneous_mbps_gpu", basic_stats([]))
        throughput_summary.setdefault("long_term_sum_mbps_cpu", basic_stats([]))
        throughput_summary.setdefault("long_term_sum_mbps_gpu", basic_stats([]))
        throughput_summary.setdefault("per_ue_avg_mbps_cpu", basic_stats([]))
        throughput_summary.setdefault("per_ue_avg_mbps_gpu", basic_stats([]))
        for row in ue_kpi:
            row.setdefault("cell_id", -1)
            row.setdefault("ue_local_id", row.get("ue_id", -1))
            row.setdefault("flow_drop_rate", row.get("drop_rate", 0.0))
            row.setdefault("drop_rate", row.get("flow_drop_rate", 0.0))
            row.setdefault("avg_mcs_tx_only", row.get("avg_mcs", 0.0))
            row.setdefault("avg_mcs_all_tti0", row.get("avg_mcs", 0.0))
            row.setdefault("avg_mcs", row.get("avg_mcs_tx_only", 0.0))
            row.setdefault("goodput_bytes", None)
            row.setdefault("goodput_mbps", None)
            row.setdefault("scheduled_tti_count", row.get("mcs_samples", 0))
            row.setdefault("no_tx_tti_count", 0)
            row.setdefault("scheduled_ratio", 1.0 if row.get("mcs_samples", 0) > 0 else 0.0)
            row.setdefault("avg_selected_layers_tx_only", 1.0 if row.get("scheduled_tti_count", 0) > 0 else -1.0)
            row.setdefault("avg_selected_layers_all_tti", row.get("avg_selected_layers_tx_only", 0.0) * row.get("scheduled_ratio", 0.0))
            row.setdefault("avg_wb_sinr_db", 0.0)
            row.setdefault("avg_sched_wb_sinr_db", 0.0)
            row.setdefault("avg_predicted_bler", 0.0)
            row.setdefault("tb_err_count", 0)
            row.setdefault("tb_bler", row.get("tx_drop_rate", 0.0))
            row.setdefault("tx_success_rate", 0.0)
            row.setdefault("tx_drop_rate", 0.0)
            row.setdefault("tx_total_pkts", 0)
            row.setdefault("tx_success_pkts", 0)
            row.setdefault("generated_bytes", 0)
            row.setdefault("accepted_bytes", row.get("generated_bytes", 0))
            row.setdefault("dropped_bytes", 0)
            row.setdefault("flow_queued_bytes", 0)
            row.setdefault("mac_buffer_bytes", 0)
            row.setdefault("mcs_samples", 0)
            row.setdefault("packet_delay_served_pkt_count", 0)
            row.setdefault("packet_delay_pending_pkt_count", 0)
            row.setdefault("packet_delay_mean_ms", 0.0)
            row.setdefault("packet_delay_p50_ms", 0.0)
            row.setdefault("packet_delay_p90_ms", 0.0)
            row.setdefault("packet_delay_p95_ms", 0.0)
            row.setdefault("packet_delay_max_ms", 0.0)
        ue_kpi.sort(key=lambda x: (x["cell_id"], x["ue_local_id"], x["ue_id"]))
    else:
        raise FileNotFoundError(f"Cannot find output or summary file in {out_dir}")

    if traffic_kpi is None:
        flow_count = int(
            round((len(ue_avg_gpu) if ue_avg_gpu else len(ue_avg_cpu)) * args.traffic_percent / 100.0)
        )
        offered_bytes_per_tti_est = flow_count * args.packet_size_bytes * args.traffic_arrival_rate
        slot_s = args.slot_duration_ms / 1000.0
        offered_mbps_est = (offered_bytes_per_tti_est * 8.0 / slot_s) / 1e6 if slot_s > 0 else 0.0
        traffic_kpi = {
            "flows": flow_count,
            "generated_pkts": None,
            "generated_bytes": None,
            "accepted_bytes": None,
            "dropped_bytes": None,
            "flow_queued_bytes": None,
            "mac_buffer_bytes": None,
            "served_bytes_est": None,
            "expired_bytes": 0,
            "expired_packets": 0,
            "expiry_drop_rate": 0.0,
            "goodput_bytes": None,
            "offered_mbps": offered_mbps_est,
            "served_mbps_est": basic_stats(throughput_ins_mbps)["mean"],
            "goodput_mbps": None,
            "drop_rate": None,
            "queue_delay_est_ms": None,
            "packet_delay_served_pkt_count": 0,
            "packet_delay_pending_pkt_count": 0,
            "packet_delay_mean_ms": 0.0,
            "packet_delay_p50_ms": 0.0,
            "packet_delay_p90_ms": 0.0,
            "packet_delay_p95_ms": 0.0,
            "packet_delay_max_ms": 0.0,
            "note": "Traffic counters were not found in run.log; offered load is estimated from CLI args.",
        }
    traffic_kpi.setdefault("packet_delay_served_pkt_count", 0)
    traffic_kpi.setdefault("packet_delay_pending_pkt_count", 0)
    traffic_kpi.setdefault("packet_delay_mean_ms", 0.0)
    traffic_kpi.setdefault("packet_delay_p50_ms", 0.0)
    traffic_kpi.setdefault("packet_delay_p90_ms", 0.0)
    traffic_kpi.setdefault("packet_delay_p95_ms", 0.0)
    traffic_kpi.setdefault("packet_delay_max_ms", 0.0)
    traffic_kpi.setdefault("expired_bytes", 0)
    traffic_kpi.setdefault("expired_packets", 0)
    traffic_kpi.setdefault("expiry_drop_rate", 0.0)
    traffic_kpi.setdefault("goodput_bytes", None)
    traffic_kpi.setdefault("goodput_mbps", None)

    cell_kpi = summarize_cell_kpi(ue_kpi)
    global_kpi = summarize_global_kpi(ue_kpi, cell_kpi, traffic_kpi, bandwidth_hz, prg_kpi)
    tti_count = len(sum_ins_gpu) if sum_ins_gpu else len(sum_ins_cpu) if sum_ins_cpu else int((existing or {}).get("tti_count", 0))
    ue_count = len(ue_avg_gpu) if ue_avg_gpu else len(ue_avg_cpu) if ue_avg_cpu else len(ue_kpi) if ue_kpi else int((existing or {}).get("ue_count", 0))
    cpu_gpu_compare = build_cpu_gpu_compare(throughput_summary, execution_mode)
    metric_sources = {
        "throughput.instantaneous_mbps_cpu": "output_short/output.txt arrays from CPU scheduler path",
        "throughput.instantaneous_mbps_gpu": "output_short/output.txt arrays from GPU scheduler path",
        "throughput.long_term_sum_mbps_cpu": "output_short/output.txt arrays from CPU scheduler path",
        "throughput.long_term_sum_mbps_gpu": "output_short/output.txt arrays from GPU scheduler path",
        "throughput.per_ue_avg_mbps_cpu": "output_short/output.txt arrays from CPU scheduler path",
        "throughput.per_ue_avg_mbps_gpu": "output_short/output.txt arrays from GPU scheduler path",
        "traffic": "run.log TRAFFIC_KPI / TRAFFIC_GOODPUT / TRAFFIC_EXPIRY lines emitted from CPU-side state",
        "prg_utilization": "run.log PRG_UTILIZATION line emitted from CPU-side scheduling solutions",
        "per_ue_kpi": "run.log UE_KPI and UE_GOODPUT lines emitted from CPU-side state",
        "per_cell_kpi": "derived from CPU-side per_ue_kpi",
        "global_kpi": "derived mainly from CPU-side traffic/per_ue_kpi",
        "cpu_gpu_compare": "derived from CPU/GPU throughput arrays in output_short/output.txt",
    }
    if execution_mode == "gpu":
        metric_sources["cpu_gpu_compare"] = (
            "disabled in gpu-only mode: CPU throughput arrays come from shadow/replay bookkeeping rather than an independent CPU reference scheduler path"
        )
    metric_notes = {
        "throughput": "These series come from scheduler avgRates/sumCellThrRecords state arrays, which are long-term internal scheduler-rate metrics rather than traffic-counter served throughput.",
        "traffic": "These values come from traffic generator, residual MAC buffer counters, and successful-TB byte accounting on the CPU-side execution path.",
        "global_kpi": "Most global KPI values are derived from CPU-side UE_KPI and TRAFFIC_KPI logs, so they should be compared against CPU-path runs unless both paths implement the same algorithm.",
        "packet_delay": "Packet-delay statistics come from a MAC packet queue tracker. Delay is measured from the TTI when packet bytes are enqueued into the MAC queue to the TTI when the last byte is drained from that queue.",
    }

    summary = {
        "run_dir": str(out_dir),
        "execution_mode": execution_mode,
        "slot_duration_ms": args.slot_duration_ms,
        "configured_bandwidth_hz": bandwidth_hz,
        "traffic_packet_bytes": args.packet_size_bytes,
        "traffic_arrival_rate_pkt_per_tti": args.traffic_arrival_rate,
        "tti_count": tti_count,
        "ue_count": ue_count,
        "metric_sources": metric_sources,
        "metric_notes": metric_notes,
        "metric_definitions": METRIC_DEFINITIONS,
        "throughput": throughput_summary,
        "cpu_gpu_compare": cpu_gpu_compare,
        "traffic": traffic_kpi,
        "prg_utilization": prg_kpi,
        "global_kpi": global_kpi,
        "per_ue_kpi": ue_kpi,
        "per_cell_kpi": cell_kpi,
    }

    summary_txt = out_dir / "kpi_summary.txt"
    ue_kpi_csv = out_dir / "ue_kpi.csv"
    summary_json.write_text(json.dumps(summary, indent=2, ensure_ascii=False))

    lines = [
        f"run_dir: {summary['run_dir']}",
        f"execution_mode: {summary.get('execution_mode', 'both')}",
        f"tti_count: {summary['tti_count']}",
        f"ue_count: {summary['ue_count']}",
        "",
        "[Throughput CPU]",
        format_metric_line("throughput.instantaneous_mbps_cpu", f"mean={summary['throughput']['instantaneous_mbps_cpu']['mean']:.6f}, p50={summary['throughput']['instantaneous_mbps_cpu']['p50']:.6f}, p95={summary['throughput']['instantaneous_mbps_cpu']['p95']:.6f}, last={summary['throughput']['instantaneous_mbps_cpu']['last']:.6f}"),
        format_metric_line("throughput.long_term_sum_mbps_cpu", f"last={summary['throughput']['long_term_sum_mbps_cpu']['last']:.6f}"),
        format_metric_line("throughput.per_ue_avg_mbps_cpu", f"p5={summary['throughput']['per_ue_avg_mbps_cpu']['p5']:.6f}, mean={summary['throughput']['per_ue_avg_mbps_cpu']['mean']:.6f}"),
        "",
        "[Throughput GPU]",
        format_metric_line("throughput.instantaneous_mbps_gpu", f"mean={summary['throughput']['instantaneous_mbps_gpu']['mean']:.6f}, p50={summary['throughput']['instantaneous_mbps_gpu']['p50']:.6f}, p95={summary['throughput']['instantaneous_mbps_gpu']['p95']:.6f}, last={summary['throughput']['instantaneous_mbps_gpu']['last']:.6f}"),
        format_metric_line("throughput.long_term_sum_mbps_gpu", f"last={summary['throughput']['long_term_sum_mbps_gpu']['last']:.6f}"),
        format_metric_line("throughput.per_ue_avg_mbps_gpu", f"p5={summary['throughput']['per_ue_avg_mbps_gpu']['p5']:.6f}, mean={summary['throughput']['per_ue_avg_mbps_gpu']['mean']:.6f}"),
        "",
        "[CPU-GPU Compare]",
        f"disabled_in_gpu_only: {summary['cpu_gpu_compare'].get('disabled_in_gpu_only', False)}",
        "",
        "[Traffic]",
        format_metric_line("traffic.flows", summary['traffic']['flows']),
        format_metric_line("traffic.offered_mbps", summary['traffic']['offered_mbps'] if summary['traffic']['offered_mbps'] is not None else 'N/A'),
        format_metric_line("traffic.served_mbps_est", summary['traffic']['served_mbps_est'] if summary['traffic']['served_mbps_est'] is not None else 'N/A'),
        format_metric_line("traffic.goodput_mbps", summary['traffic']['goodput_mbps'] if summary['traffic']['goodput_mbps'] is not None else 'N/A'),
        format_metric_line("traffic.drop_rate", summary['traffic']['drop_rate'] if summary['traffic']['drop_rate'] is not None else 'N/A'),
        format_metric_line("traffic.expired_bytes", summary['traffic']['expired_bytes']),
        format_metric_line("traffic.expired_packets", summary['traffic']['expired_packets']),
        format_metric_line("traffic.expiry_drop_rate", f"{summary['traffic']['expiry_drop_rate']:.6f}"),
        format_metric_line("traffic.queue_delay_est_ms", summary['traffic']['queue_delay_est_ms'] if summary['traffic']['queue_delay_est_ms'] is not None else 'N/A'),
        format_metric_line("traffic.packet_delay_mean_ms", f"{summary['traffic']['packet_delay_mean_ms']:.6f}"),
        format_metric_line("traffic.packet_delay_p50_ms", f"{summary['traffic']['packet_delay_p50_ms']:.6f}"),
        format_metric_line("traffic.packet_delay_p90_ms", f"{summary['traffic']['packet_delay_p90_ms']:.6f}"),
        format_metric_line("traffic.packet_delay_p95_ms", f"{summary['traffic']['packet_delay_p95_ms']:.6f}"),
        "",
        "[Global KPI]",
        format_metric_line("global_kpi.cluster_sum_throughput_mbps", f"{summary['global_kpi']['cluster_sum_throughput_mbps']:.6f}"),
        format_metric_line("global_kpi.cluster_goodput_mbps", summary['global_kpi']['cluster_goodput_mbps'] if summary['global_kpi']['cluster_goodput_mbps'] is not None else 'N/A'),
        format_metric_line("global_kpi.cluster_spectral_efficiency_bps_per_hz", f"{summary['global_kpi']['cluster_spectral_efficiency_bps_per_hz']:.6f}"),
        format_metric_line("global_kpi.average_ue_throughput_mbps", f"{summary['global_kpi']['average_ue_throughput_mbps']:.6f}"),
        format_metric_line("global_kpi.average_ue_goodput_mbps", summary['global_kpi']['average_ue_goodput_mbps'] if summary['global_kpi']['average_ue_goodput_mbps'] is not None else 'N/A'),
        format_metric_line("global_kpi.global_tb_bler", f"{summary['global_kpi']['global_tb_bler']:.6f}"),
        format_metric_line("global_kpi.total_expired_bytes", summary['global_kpi']['total_expired_bytes']),
        format_metric_line("global_kpi.total_expired_packets", summary['global_kpi']['total_expired_packets']),
        format_metric_line("global_kpi.expiry_drop_rate", f"{summary['global_kpi']['expiry_drop_rate']:.6f}"),
        format_metric_line("global_kpi.residual_buffer_ratio", f"{summary['global_kpi']['residual_buffer_ratio']:.6f}"),
        format_metric_line("global_kpi.non_residual_buffer_ratio", f"{summary['global_kpi']['non_residual_buffer_ratio']:.6f}"),
        format_metric_line("global_kpi.served_buffer_ratio", f"{summary['global_kpi']['served_buffer_ratio']:.6f}"),
        format_metric_line("global_kpi.ue_throughput_jain", f"{summary['global_kpi']['ue_throughput_jain']:.6f}"),
        format_metric_line("global_kpi.ue_goodput_jain", summary['global_kpi']['ue_goodput_jain'] if summary['global_kpi']['ue_goodput_jain'] is not None else 'N/A'),
        format_metric_line("global_kpi.ue_throughput_p5_mbps", f"{summary['global_kpi']['ue_throughput_p5_mbps']:.6f}"),
        format_metric_line("global_kpi.ue_goodput_p5_mbps", summary['global_kpi']['ue_goodput_p5_mbps'] if summary['global_kpi']['ue_goodput_p5_mbps'] is not None else 'N/A'),
        format_metric_line("global_kpi.cell_edge_spectral_efficiency_p5_bps_per_hz", f"{summary['global_kpi']['cell_edge_spectral_efficiency_p5_bps_per_hz']:.6f}"),
        format_metric_line("global_kpi.ue_throughput_p10_mbps", f"{summary['global_kpi']['ue_throughput_p10_mbps']:.6f}"),
        format_metric_line("global_kpi.ue_goodput_p10_mbps", summary['global_kpi']['ue_goodput_p10_mbps'] if summary['global_kpi']['ue_goodput_p10_mbps'] is not None else 'N/A'),
        format_metric_line("global_kpi.scheduled_ratio_jain", f"{summary['global_kpi']['scheduled_ratio_jain']:.6f}"),
        format_metric_line("global_kpi.scheduled_ratio_p5", f"{summary['global_kpi']['scheduled_ratio_p5']:.6f}"),
        format_metric_line(
            "global_kpi.prg_utilization_ratio",
            "N/A" if summary["global_kpi"]["prg_utilization_ratio"] is None else f"{summary['global_kpi']['prg_utilization_ratio']:.6f}",
        ),
        format_metric_line("global_kpi.queue_delay_p95_ms", f"{summary['global_kpi']['queue_delay_p95_ms']:.6f}"),
        format_metric_line("global_kpi.packet_delay_p95_ms", f"{summary['global_kpi']['packet_delay_p95_ms']:.6f}"),
        format_metric_line("global_kpi.ue_fraction_queue_delay_gt_10s", f"{summary['global_kpi']['ue_fraction_queue_delay_gt_10s']:.6f}"),
        format_metric_line("global_kpi.ue_fraction_queue_delay_gt_20s", f"{summary['global_kpi']['ue_fraction_queue_delay_gt_20s']:.6f}"),
        "",
        "[Metric Sources]",
        "throughput_cpu_gpu: output_short/output.txt arrays",
        "traffic_global_per_ue: run.log CPU-side UE_KPI/UE_GOODPUT/TRAFFIC_KPI/TRAFFIC_GOODPUT/TRAFFIC_EXPIRY",
        "note: throughput arrays are scheduler internal avg-rate metrics, not packet-served throughput",
    ]
    traffic_idx = lines.index("[Traffic]")
    if summary["cpu_gpu_compare"].get("disabled_in_gpu_only"):
        lines.insert(traffic_idx, f"disabled_reason: {summary['cpu_gpu_compare'].get('disabled_reason', 'N/A')}")
        lines.insert(traffic_idx + 1, "")
    else:
        compare_lines = [
            format_metric_line("cpu_gpu_compare.long_term_sum_mean_mbps_cpu", f"{summary['cpu_gpu_compare']['long_term_sum_mean_mbps_cpu']:.6f}"),
            format_metric_line("cpu_gpu_compare.long_term_sum_mean_mbps_gpu", f"{summary['cpu_gpu_compare']['long_term_sum_mean_mbps_gpu']:.6f}"),
            format_metric_line("cpu_gpu_compare.long_term_sum_mean_gpu_minus_cpu_mbps", f"{summary['cpu_gpu_compare']['long_term_sum_mean_gpu_minus_cpu_mbps']:.6f}"),
            format_metric_line("cpu_gpu_compare.long_term_sum_mean_gpu_over_cpu_ratio", summary['cpu_gpu_compare']['long_term_sum_mean_gpu_over_cpu_ratio'] if summary['cpu_gpu_compare']['long_term_sum_mean_gpu_over_cpu_ratio'] is not None else 'N/A'),
            format_metric_line("cpu_gpu_compare.long_term_sum_last_mbps_cpu", f"{summary['cpu_gpu_compare']['long_term_sum_last_mbps_cpu']:.6f}"),
            format_metric_line("cpu_gpu_compare.long_term_sum_last_mbps_gpu", f"{summary['cpu_gpu_compare']['long_term_sum_last_mbps_gpu']:.6f}"),
            format_metric_line("cpu_gpu_compare.long_term_sum_last_gpu_minus_cpu_mbps", f"{summary['cpu_gpu_compare']['long_term_sum_last_gpu_minus_cpu_mbps']:.6f}"),
            format_metric_line("cpu_gpu_compare.long_term_sum_last_gpu_over_cpu_ratio", summary['cpu_gpu_compare']['long_term_sum_last_gpu_over_cpu_ratio'] if summary['cpu_gpu_compare']['long_term_sum_last_gpu_over_cpu_ratio'] is not None else 'N/A'),
            "",
        ]
        for idx, line in enumerate(compare_lines):
            lines.insert(traffic_idx + idx, line)
    if "note" in summary["traffic"]:
        lines.append(f"note: {summary['traffic']['note']}")

    summary_txt.write_text("\n".join(lines) + "\n")
    if ue_kpi:
        csv_lines = [
            "cell_id,ue_local_id,ue_id,avg_thr_mbps,goodput_bytes,goodput_mbps,avg_mcs_tx_only,avg_mcs_all_tti0,avg_selected_layers_tx_only,avg_selected_layers_all_tti,scheduled_tti_count,no_tx_tti_count,scheduled_ratio,avg_wb_sinr_db,avg_sched_wb_sinr_db,avg_predicted_bler,tb_err_count,tb_bler,tx_success_rate,tx_drop_rate,tx_total_pkts,tx_success_pkts,queue_delay_est_ms,packet_delay_served_pkt_count,packet_delay_pending_pkt_count,packet_delay_mean_ms,packet_delay_p50_ms,packet_delay_p90_ms,packet_delay_p95_ms,packet_delay_max_ms,generated_bytes,accepted_bytes,dropped_bytes,flow_queued_bytes,mac_buffer_bytes,mcs_samples"
        ]
        for r in ue_kpi:
            goodput_bytes_csv = "" if r.get("goodput_bytes") is None else str(r["goodput_bytes"])
            goodput_mbps_csv = "" if r.get("goodput_mbps") is None else f"{r['goodput_mbps']:.6f}"
            csv_lines.append(
                f"{r['cell_id']},{r['ue_local_id']},{r['ue_id']},{r['avg_thr_mbps']:.6f},{goodput_bytes_csv},{goodput_mbps_csv},{r['avg_mcs_tx_only']:.6f},{r['avg_mcs_all_tti0']:.6f},{r['avg_selected_layers_tx_only']:.6f},{r['avg_selected_layers_all_tti']:.6f},{r['scheduled_tti_count']},{r['no_tx_tti_count']},{r['scheduled_ratio']:.6f},{r['avg_wb_sinr_db']:.6f},{r['avg_sched_wb_sinr_db']:.6f},{r['avg_predicted_bler']:.6f},{r['tb_err_count']},{r['tb_bler']:.6f},{r['tx_success_rate']:.6f},{r['tx_drop_rate']:.6f},{r['tx_total_pkts']},{r['tx_success_pkts']},{r['queue_delay_est_ms']:.6f},{r['packet_delay_served_pkt_count']},{r['packet_delay_pending_pkt_count']},{r['packet_delay_mean_ms']:.6f},{r['packet_delay_p50_ms']:.6f},{r['packet_delay_p90_ms']:.6f},{r['packet_delay_p95_ms']:.6f},{r['packet_delay_max_ms']:.6f},{r['generated_bytes']},{r['accepted_bytes']},{r['dropped_bytes']},{r['flow_queued_bytes']},{r['mac_buffer_bytes']},{r['mcs_samples']}"
            )
        cell_kpi = summary["per_cell_kpi"]
        if cell_kpi:
            csv_lines.append("")
            csv_lines.append("# CELL_KPI")
            csv_lines.append(
                "cell_id,ue_count,cell_sum_thr_mbps,cell_sum_goodput_mbps,cell_avg_ue_thr_mbps,cell_avg_ue_goodput_mbps,cell_avg_mcs_tx_only,cell_avg_mcs_all_tti0,cell_scheduled_tti_count,cell_no_tx_tti_count,cell_scheduled_ratio,cell_avg_wb_sinr_db,cell_avg_sched_wb_sinr_db,cell_avg_predicted_bler,cell_tb_err_count,cell_tb_bler,cell_tx_success_rate,cell_tx_drop_rate,cell_tx_total_pkts,cell_tx_success_pkts,cell_avg_queue_delay_est_ms,cell_total_generated_bytes,cell_total_mac_buffer_bytes,cell_total_goodput_bytes,cell_total_mcs_samples"
            )
            for r in cell_kpi:
                cell_sum_goodput_csv = "" if r.get("cell_sum_goodput_mbps") is None else f"{r['cell_sum_goodput_mbps']:.6f}"
                cell_avg_goodput_csv = "" if r.get("cell_avg_ue_goodput_mbps") is None else f"{r['cell_avg_ue_goodput_mbps']:.6f}"
                cell_total_goodput_bytes_csv = "" if r.get("cell_total_goodput_bytes") is None else str(r["cell_total_goodput_bytes"])
                csv_lines.append(
                    f"{r['cell_id']},{r['ue_count']},{r['cell_sum_thr_mbps']:.6f},{cell_sum_goodput_csv},{r['cell_avg_ue_thr_mbps']:.6f},{cell_avg_goodput_csv},{r['cell_avg_mcs_tx_only']:.6f},{r['cell_avg_mcs_all_tti0']:.6f},{r['cell_scheduled_tti_count']},{r['cell_no_tx_tti_count']},{r['cell_scheduled_ratio']:.6f},{r['cell_avg_wb_sinr_db']:.6f},{r['cell_avg_sched_wb_sinr_db']:.6f},{r['cell_avg_predicted_bler']:.6f},{r['cell_tb_err_count']},{r['cell_tb_bler']:.6f},{r['cell_tx_success_rate']:.6f},{r['cell_tx_drop_rate']:.6f},{r['cell_tx_total_pkts']},{r['cell_tx_success_pkts']},{r['cell_avg_queue_delay_est_ms']:.6f},{r['cell_total_generated_bytes']},{r['cell_total_mac_buffer_bytes']},{cell_total_goodput_bytes_csv},{r['cell_total_mcs_samples']}"
                )
        csv_lines.append("")
        csv_lines.append("# GLOBAL_KPI")
        csv_lines.append("metric,value,note")
        for k, v in summary["global_kpi"].items():
            csv_lines.append(f"{k},{format_metric_value(v)},{metric_note(f'global_kpi.{k}')}")
        csv_lines.append("")
        csv_lines.append("# FIELD_DEFINITIONS")
        csv_lines.append("scope,field,note")
        append_definition_rows(csv_lines, "per_ue_kpi", UE_KPI_FIELD_ORDER)
        append_definition_rows(csv_lines, "per_cell_kpi", CELL_KPI_FIELD_ORDER)
        append_definition_rows(csv_lines, "cpu_gpu_compare", CPU_GPU_COMPARE_FIELD_ORDER)
        for metric_name in sorted(k for k in METRIC_DEFINITIONS if k.startswith("global_kpi.") or k.startswith("traffic.") or k.startswith("throughput.")):
            scope, field = metric_name.split(".", 1)
            csv_lines.append(f"{scope},{field},{metric_note(metric_name)}")
        ue_kpi_csv.write_text("\n".join(csv_lines) + "\n")
    print(f"KPI summary written: {summary_json}")
    print(f"KPI summary written: {summary_txt}")
    if ue_kpi:
        print(f"UE KPI written: {ue_kpi_csv}")


if __name__ == "__main__":
    main()
